sudo: false
language: java
dist: trusty

before_script:
  - export JDK8_HOME=$(jdk_switcher home oraclejdk8)
  - export JDK9_HOME=/usr/lib/jvm/java-9-oracle
  - test -d "${JDK8_HOME}" || export JDK8_HOME=${JDK9_HOME}

before_cache:
  # No sense in caching current build artifacts
  - rm -rf $HOME/.m2/repository/com/tomoncle
cache:
  directories:
    - $HOME/.m2/repository

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
      env:
        - JDK=8

install: /bin/true
script:
  # package from model spring-boot-config-samples-tomcat-autoscan
  # ignore model spring-boot-config-samples-tomcat-mail
  - mvn package -rf spring-boot-config-samples-tomcat-autoscan -Dmaven.javadoc.skip=true -V -B -e
